"""add outreach reply threading

Revision ID: 39e5b533cc8a
Revises: 20260602_0002
Create Date: 2026-08-25 09:40:19.263562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e5b533cc8a'
down_revision: Union[str, Sequence[str], None] = '20260602_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('thread_id', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('message_id_header', sa.String(), nullable=True))
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.add_column('outreach_logs', sa.Column('is_reply', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('outreach_logs', sa.Column('threaded', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('sync_jobs', 'sync_scope',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sync_jobs', 'synced_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_jobs', 'synced_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sync_jobs', 'sync_scope',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'days'::character varying"),
               existing_nullable=False)
    op.drop_column('outreach_logs', 'threaded')
    op.drop_column('outreach_logs', 'is_reply')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_column('emails', 'message_id_header')
    op.drop_column('emails', 'thread_id')
    # ### end Alembic commands ###
