"""change_experience_to_string

Revision ID: 8c4dc07554f0
Revises: 6192b5e043fd
Create Date: 2026-05-08 11:55:37.567079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4dc07554f0'
down_revision: Union[str, Sequence[str], None] = '6192b5e043fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('hr_user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['hr_user_id'], ['hr_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attachment_id', 'hr_user_id', name='uix_attachment_hr_user')
    )
    op.create_index(op.f('ix_attachment_views_attachment_id'), 'attachment_views', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_attachment_views_hr_user_id'), 'attachment_views', ['hr_user_id'], unique=False)
    op.create_index(op.f('ix_attachment_views_id'), 'attachment_views', ['id'], unique=False)
    op.alter_column('attachments', 'experience',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'experience',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_attachment_views_id'), table_name='attachment_views')
    op.drop_index(op.f('ix_attachment_views_hr_user_id'), table_name='attachment_views')
    op.drop_index(op.f('ix_attachment_views_attachment_id'), table_name='attachment_views')
    op.drop_table('attachment_views')
    # ### end Alembic commands ###
