"""remove columns from attachments

Revision ID: 9076afcac9f0
Revises: 8c4dc07554f0
Create Date: 2026-05-11 10:14:36.138002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9076afcac9f0'
down_revision: Union[str, Sequence[str], None] = '8c4dc07554f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'file_size')
    op.drop_column('attachments', 'github')
    op.drop_column('attachments', 'linkedin')
    op.drop_column('attachments', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('linkedin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
